data = {
    '*': 'v2, data alignment protocol',
    100: {
        '*': {'en': 'resource'},
        110: {'en': 'record'},
        120: {'en': 'event'},
        130: {'en': 'document'},
        140: {'en': 'material'},
        150: {'en': 'location'},
        151: {'en': 'location:address'},
        152: {'en': 'location:account'},
        153: {'en': 'location:url'},
        200: {'en': 'CATEGORY'},
        300: {'en': 'SYSTEM'},
        400: {'en': 'METHOD'},
        500: {'en': 'OPERATION'},
    },
    200: {
        '*': {'en': 'category'},
        210: {'en': 'goal'},
        220: {'en': 'concept'},
        230: {'en': 'question'},
    },
    300: {
        '*': {'en': 'system'},
        310: {'en': 'structure'},
        320: {'en': 'mechanism'},
        330: {'en': 'organization'},
        340: {'en': 'process'},
        350: {'en': 'api'},
        360: {'en': 'project'},
        370: {'en': 'person'},
    },
    400: {
        '*': {'en': 'method'},
        410: {'en': 'idea'},
        420: {'en': 'principle'},
        430: {'en': 'function'},
        440: {'en': 'invention'},
        450: {'en': 'endpoint'},
        460: {'en': 'product'},
        470: {'en': 'equipment'},
        300: {'en': 'SYSTEM'},
    },
    500: {
        '*': {'en': 'operation'},
        510: {'en': 'call'},
        511: {'en': 'call:query'},
        520: {'en': 'order'},
        521: {'en': 'order:buy'},
        522: {'en': 'order:sell'},
        523: {'en': 'order:transfer'},
        524: {'en': 'order:machining'},
        525: {'en': 'order:shipment'},
        526: {'en': 'order:payment'},
        527: {'en': 'order:contract'},
        530: {'en': 'task'},
        531: {'en': 'task:programming'},
        532: {'en': 'task:engineering'},
        533: {'en': 'task:manufacturing'},
        534: {'en': 'task:treatment'},
        200: {'en': 'CATEGORY'},
    },
}
