data = {
    '*': {'en': 'v2, data alignment protocol', 'cn': 'v2, 数据对齐协议'},
    100: {
        '*': {'en': 'resource', 'cn': '资源'},
        110: {'en': 'record', 'cn': '记录'},
        120: {'en': 'event', 'cn': '事件'},
        130: {'en': 'document', 'cn': '文档'},
        140: {'en': 'material', 'cn': '资料'},
        150: {'en': 'location', 'cn': '位置'},
        151: {'en': 'location:address', 'cn': '位置:地址'},
        152: {'en': 'location:account', 'cn': '位置:账户'},
        153: {'en': 'location:url', 'cn': '位置:网址'},
        200: {'en': 'CATEGORY', 'cn': '分类'},
        300: {'en': 'SYSTEM', 'cn': '系统'},
        400: {'en': 'METHOD', 'cn': '方法'},
        500: {'en': 'OPERATION', 'cn': '操作'},
    },
    200: {
        '*': {'en': 'category', 'cn': '分类'},
        210: {'en': 'goal', 'cn': '目标'},
        220: {'en': 'concept', 'cn': '概念'},
        230: {'en': 'question', 'cn': '问题'},
    },
    300: {
        '*': {'en': 'system', 'cn': '系统'},
        310: {'en': 'structure', 'cn': '结构'},
        320: {'en': 'mechanism', 'cn': '机制'},
        330: {'en': 'organization', 'cn': '组织'},
        340: {'en': 'process', 'cn': '过程'},
        350: {'en': 'api', 'cn': 'API'},
        360: {'en': 'project', 'cn': '项目'},
        370: {'en': 'person', 'cn': '个人'},
        200: {'en': 'CATEGORY', 'cn': '分类'},
    },
    400: {
        '*': {'en': 'method', 'cn': '方法'},
        410: {'en': 'idea', 'cn': '想法'},
        420: {'en': 'principle', 'cn': '原理'},
        430: {'en': 'procedure', 'cn': '程序'},
        440: {'en': 'function', 'cn': '函数'},
        450: {'en': 'invention', 'cn': '发明'},
        460: {'en': 'endpoint', 'cn': '端点'},
        470: {'en': 'product', 'cn': '产品'},
        480: {'en': 'equipment', 'cn': '设备'},
        300: {'en': 'SYSTEM', 'cn': '系统'},
    },
    500: {
        '*': {'en': 'operation', 'cn': '操作'},
        510: {'en': 'call', 'cn': '调用'},
        511: {'en': 'call:query', 'cn': '调用:询问'},
        520: {'en': 'order', 'cn': '订单'},
        521: {'en': 'order:buy', 'cn': '订单:买单'},
        522: {'en': 'order:sell', 'cn': '订单:卖单'},
        523: {'en': 'order:transfer', 'cn': '订单:转移'},
        524: {'en': 'order:machining', 'cn': '订单:加工'},
        525: {'en': 'order:shipment', 'cn': '订单:发货'},
        526: {'en': 'order:payment', 'cn': '订单:付款'},
        527: {'en': 'order:contract', 'cn': '订单:合约'},
        530: {'en': 'task', 'cn': '任务'},
        531: {'en': 'task:programming', 'cn': '任务:编程'},
        532: {'en': 'task:engineering', 'cn': '任务:工程'},
        533: {'en': 'task:manufacturing', 'cn': '任务:制造'},
        534: {'en': 'task:treatment', 'cn': '任务:处理'},
        200: {'en': 'CATEGORY', 'cn': '分类'},
    },
}
