data = {
    '*': {'en': 'v2, data alignment protocol', 'cn': 'v2, 数据对齐协议', 'lt': 'v2, duomenų apjungimo protokolas'},
    100: {
        '*': {'en': 'resource', 'cn': '资源', 'lt': 'resursas'},
        110: {'en': 'record', 'cn': '记录', 'lt': 'įrašas'},
        120: {'en': 'event', 'cn': '事件', 'lt': 'įvykis'},
        130: {'en': 'document', 'cn': '文档', 'lt': 'dokumentas'},
        140: {'en': 'material', 'cn': '资料', 'lt': 'medžiaga'},
        150: {'en': 'location', 'cn': '位置', 'lt': 'vieta'},
        151: {'en': 'location:address', 'cn': '位置:地址', 'lt': 'vieta:adresas'},
        152: {'en': 'location:account', 'cn': '位置:账户', 'lt': 'vieta:sąskaita'},
        153: {'en': 'location:url', 'cn': '位置:网址', 'lt': 'vieta:url'},
        200: {'en': 'CATEGORY', 'cn': '分类', 'lt': 'KATEGORIJA'},
        300: {'en': 'SYSTEM', 'cn': '系统', 'lt': 'SISTEMA'},
        400: {'en': 'METHOD', 'cn': '方法', 'lt': 'METODAS'},
        500: {'en': 'OPERATION', 'cn': '操作', 'lt': 'OPERACIJA'},
    },
    200: {
        '*': {'en': 'category', 'cn': '分类', 'lt': 'kategorija'},
        210: {'en': 'goal', 'cn': '目标', 'lt': 'tikslas'},
        220: {'en': 'concept', 'cn': '概念', 'lt': 'sąvoka'},
        230: {'en': 'question', 'cn': '问题', 'lt': 'klausimas'},
    },
    300: {
        '*': {'en': 'system', 'cn': '系统', 'lt': 'sistema'},
        310: {'en': 'structure', 'cn': '结构', 'lt': 'struktūra'},
        320: {'en': 'mechanism', 'cn': '机制', 'lt': 'mechanizmas'},
        330: {'en': 'organization', 'cn': '组织', 'lt': 'organizacija'},
        340: {'en': 'process', 'cn': '过程', 'lt': 'procesas'},
        350: {'en': 'api', 'cn': 'api', 'lt': 'api'},
        360: {'en': 'project', 'cn': '项目', 'lt': 'projektas'},
        370: {'en': 'person', 'cn': '个人', 'lt': 'individas'},
        200: {'en': 'CATEGORY', 'cn': '分类', 'lt': 'KATEGORIJA'},
    },
    400: {
        '*': {'en': 'method', 'cn': '方法', 'lt': 'metodas'},
        410: {'en': 'idea', 'cn': '想法', 'lt': 'idėja'},
        420: {'en': 'principle', 'cn': '原理', 'lt': 'principas'},
        430: {'en': 'procedure', 'cn': '程序', 'lt': 'procedūra'},
        440: {'en': 'function', 'cn': '函数', 'lt': 'funkcija'},
        450: {'en': 'invention', 'cn': '发明', 'lt': 'išradimas'},
        460: {'en': 'endpoint', 'cn': '端点', 'lt': 'terminalas'},
        470: {'en': 'product', 'cn': '产品', 'lt': 'produktas'},
        480: {'en': 'equipment', 'cn': '设备', 'lt': 'įranga'},
        300: {'en': 'SYSTEM', 'cn': '系统', 'lt': 'SISTEMA'},
    },
    500: {
        '*': {'en': 'operation', 'cn': '操作', 'lt': 'operacija'},
        510: {'en': 'call', 'cn': '调用', 'lt': 'kvietimas'},
        511: {'en': 'call:query', 'cn': '调用:询问', 'lt': 'kvietimas:užklausa'},
        520: {'en': 'order', 'cn': '订单', 'lt': 'orderis'},
        521: {'en': 'order:buy', 'cn': '订单:买单', 'lt': 'orderis:pirkimo'},
        522: {'en': 'order:sell', 'cn': '订单:卖单', 'lt': 'orderis:pardavimo'},
        523: {'en': 'order:transfer', 'cn': '订单:转移', 'lt': 'orderis:persiuntos'},
        524: {'en': 'order:machining', 'cn': '订单:加工', 'lt': 'orderis:apdirbimo'},
        525: {'en': 'order:shipment', 'cn': '订单:发货', 'lt': 'orderis:siuntos'},
        526: {'en': 'order:payment', 'cn': '订单:付款', 'lt': 'orderis:apmokėjimo'},
        527: {'en': 'order:contract', 'cn': '订单:合约', 'lt': 'orderis:sutarties'},
        530: {'en': 'task', 'cn': '任务', 'lt': 'užduotis'},
        531: {'en': 'task:programming', 'cn': '任务:编程', 'lt': 'užduotis:programavimo'},
        532: {'en': 'task:engineering', 'cn': '任务:工程', 'lt': 'užduotis:inžinerijos'},
        533: {'en': 'task:manufacturing', 'cn': '任务:制造', 'lt': 'užduotis:gamybos'},
        534: {'en': 'task:treatment', 'cn': '任务:处理', 'lt': 'užduotis:tvarkymo'},
        200: {'en': 'CATEGORY', 'cn': '分类', 'lt': 'KATEGORIJA'},
    },
}
