data = {
    '*': {'en': 'v3, data alignment protocol', 'cn': 'v3, 数据对齐协议', 'lt': 'v3, duomenų apjungimo protokolas'},
    100: {
        '*': {'en': 'resource', 'cn': '资源', 'lt': 'išteklius'},
        110: {'en': 'record', 'cn': '记录', 'lt': 'įrašas'},
        111: {'en': 'record:identifier', 'cn': '记录:识别码', 'lt': 'įrašas:identifikatorius'},
        120: {'en': 'event', 'cn': '事件', 'lt': 'įvykis'},
        130: {'en': 'document', 'cn': '文档', 'lt': 'dokumentas'},
        140: {'en': 'material', 'cn': '资料', 'lt': 'medžiaga'},
        200: {'en': 'CATEGORY', 'cn': '分类', 'lt': 'KATEGORIJA'},
        300: {'en': 'SYSTEM', 'cn': '系统', 'lt': 'SISTEMA'},
        400: {'en': 'METHOD', 'cn': '方法', 'lt': 'METODAS'},
        500: {'en': 'OPERATION', 'cn': '操作', 'lt': 'OPERACIJA'},
        500: {'en': 'LOCATION', 'cn': '位置', 'lt': 'VIETA'},
    },
    200: {
        '*': {'en': 'category', 'cn': '分类', 'lt': 'kategorija'},
        210: {'en': 'goal', 'cn': '目标', 'lt': 'tikslas'},
        220: {'en': 'concept', 'cn': '概念', 'lt': 'sąvoka'},
        230: {'en': 'question', 'cn': '问题', 'lt': 'klausimas'},
        240: {'en': 'property', 'cn': '特征', 'lt': 'savybė'},
    },
    300: {
        '*': {'en': 'method', 'cn': '方法', 'lt': 'metodas'},
        310: {'en': 'idea', 'cn': '想法', 'lt': 'idėja'},
        320: {'en': 'principle', 'cn': '原理', 'lt': 'principas'},
        330: {'en': 'procedure', 'cn': '程序', 'lt': 'procedūra'},
        340: {'en': 'function', 'cn': '函数', 'lt': 'funkcija'},
        350: {'en': 'invention', 'cn': '发明', 'lt': 'išradimas'},
        360: {'en': 'endpoint', 'cn': '端点', 'lt': 'terminalas'},
        370: {'en': 'product', 'cn': '产品', 'lt': 'produktas'},
        380: {'en': 'equipment', 'cn': '设备', 'lt': 'įranga'},
        400: {'en': 'SYSTEM', 'cn': '系统', 'lt': 'SISTEMA'},
    },
    400: {
        '*': {'en': 'system', 'cn': '系统', 'lt': 'sistema'},
        410: {'en': 'structure', 'cn': '结构', 'lt': 'struktūra'},
        411: {'en': 'structure:prototype', 'cn': '结构:原型', 'lt': 'struktūra:prototipas'},
        420: {'en': 'mechanism', 'cn': '机制', 'lt': 'mechanizmas'},
        430: {'en': 'organization', 'cn': '组织', 'lt': 'organizacija'},
        440: {'en': 'process', 'cn': '过程', 'lt': 'procesas'},
        450: {'en': 'api', 'cn': 'api', 'lt': 'api'},
        460: {'en': 'project', 'cn': '项目', 'lt': 'projektas'},
        470: {'en': 'person', 'cn': '个人', 'lt': 'individas'},
        200: {'en': 'CATEGORY', 'cn': '分类', 'lt': 'KATEGORIJA'},
    },
    500: {
        '*': {'en': 'operation', 'cn': '操作', 'lt': 'operacija'},
        510: {'en': 'call', 'cn': '调用', 'lt': 'kvietimas'},
        511: {'en': 'call:query', 'cn': '调用:询问', 'lt': 'kvietimas:užklausa'},
        520: {'en': 'order', 'cn': '订单', 'lt': 'orderis'},
        521: {'en': 'order:buy', 'cn': '订单:买单', 'lt': 'orderis:pirkimo'},
        522: {'en': 'order:sell', 'cn': '订单:卖单', 'lt': 'orderis:pardavimo'},
        523: {'en': 'order:transfer', 'cn': '订单:转移', 'lt': 'orderis:persiuntos'},
        524: {'en': 'order:machining', 'cn': '订单:加工', 'lt': 'orderis:apdirbimo'},
        525: {'en': 'order:shipment', 'cn': '订单:发货', 'lt': 'orderis:siuntos'},
        526: {'en': 'order:payment', 'cn': '订单:付款', 'lt': 'orderis:apmokėjimo'},
        527: {'en': 'order:contract', 'cn': '订单:合约', 'lt': 'orderis:sutarties'},
        528: {'en': 'order:evaluation', 'cn': '订单:评价', 'lt': 'orderis:vertinimo'},
        529: {'en': 'order:message', 'cn': '订单:消息', 'lt': 'orderis:žinutė'},
        530: {'en': 'task', 'cn': '任务', 'lt': 'užduotis'},
        531: {'en': 'task:programming', 'cn': '任务:编程', 'lt': 'užduotis:programavimo'},
        532: {'en': 'task:engineering', 'cn': '任务:工程', 'lt': 'užduotis:inžinerijos'},
        533: {'en': 'task:manufacturing', 'cn': '任务:制造', 'lt': 'užduotis:gamybos'},
        534: {'en': 'task:treatment', 'cn': '任务:处理', 'lt': 'užduotis:tvarkymo'},
        535: {'en': 'task:art', 'cn': '任务:美术', 'lt': 'užduotis:meno'},
        200: {'en': 'CATEGORY', 'cn': '分类', 'lt': 'KATEGORIJA'},
    },
    600: {
        '*': {'en': 'location', 'cn': '位置', 'lt': 'vieta'},
        610: {'en': 'address', 'cn': '地址', 'lt': 'adresas'},
        620: {'en': 'account', 'cn': '账户', 'lt': 'sąskaita'},
        630: {'en': 'url', 'cn': '网址', 'lt': 'url'},
        640: {'en': 'ledger', 'cn': '分类帐', 'lt': 'knyga'},
    }
}
